/** <?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;
/**
 * Description of module_test
 *
 * @author kana
 */

/**
* Implements hook_form_alter().
*/
function module_test_form_alter(&$form, FormStateInterface $form_state, $form_id) {
            
    if($form_id === 'system_site_information_settings' ){
        
        // change save configuration button value
        $form['actions']['submit']['#value'] = t('Update Configuration');
        
        $form['#submit'][] = 'module_test_form_submit';
    }
}

/**
* Custom submit handler for the module_testform.
*
* @param $form
* @param \Drupal\Core\Form\FormStateInterface $form_state
*/

function module_test_form_submit($form , FormStateInterface $form_state){
        
    \Drupal::messenger()->addStatus(t('the Site API Key has been saved with this ' . $form_state->getValue('siteapikey')));
     
}
